[package]
name = "rustlink"
version = "0.1.0"
authors = ["Michal Podhradsky <michal.podhradsky@galois.com>"]

[dependencies]
pprzlink = {path="/xxx/pprzlink_rust"}
ivyrust = "0.1.1"
serial="0.4"
docopt = "0.8"
serde = "1.0" # if you're using `derive(Deserialize)`
serde_derive = "1.0" # if you're using `derive(Deserialize)`
regex = "0.2"